// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9PPAlK1ihYahJVxft3F3zUZ3NrFMesdE',
    appId: '1:790555235471:web:3c98adff00dfa812114cfa',
    messagingSenderId: '790555235471',
    projectId: 'emptrack-42bf8',
    authDomain: 'emptrack-42bf8.firebaseapp.com',
    databaseURL: 'https://emptrack-42bf8-default-rtdb.firebaseio.com',
    storageBucket: 'emptrack-42bf8.appspot.com',
    measurementId: 'G-NEWX5S19VF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMHXM2oMmSosKrgXaQQVF1mn1j6CuSTmQ',
    appId: '1:790555235471:android:1f2d08d9d1bf6af7114cfa',
    messagingSenderId: '790555235471',
    projectId: 'emptrack-42bf8',
    databaseURL: 'https://emptrack-42bf8-default-rtdb.firebaseio.com',
    storageBucket: 'emptrack-42bf8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAerzNE8nTsHydZ_12FvzI78tLTfp9GYF8',
    appId: '1:790555235471:ios:65d936cc8bcfbd96114cfa',
    messagingSenderId: '790555235471',
    projectId: 'emptrack-42bf8',
    databaseURL: 'https://emptrack-42bf8-default-rtdb.firebaseio.com',
    storageBucket: 'emptrack-42bf8.appspot.com',
    iosClientId: '790555235471-0hh9thaojrie8cfqutcf4dvsqjdvcla2.apps.googleusercontent.com',
    iosBundleId: 'com.example.track',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAerzNE8nTsHydZ_12FvzI78tLTfp9GYF8',
    appId: '1:790555235471:ios:c3142f153d4d56f6114cfa',
    messagingSenderId: '790555235471',
    projectId: 'emptrack-42bf8',
    databaseURL: 'https://emptrack-42bf8-default-rtdb.firebaseio.com',
    storageBucket: 'emptrack-42bf8.appspot.com',
    iosClientId: '790555235471-2rbhs4u9a1hc1ktrj37bda1s4apkumn3.apps.googleusercontent.com',
    iosBundleId: 'com.example.track.RunnerTests',
  );
}
